# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: "IEEE DISTILL 2025"            # 1st IEEE Workshop on Distributed, Secure, and Trustworthy Intelligence with LLMs
first_name:
middle_name:
last_name:
email: "shahnewazkarim-sakib@utc.edu" # Primary contact for DISTILL 2025
description: >                       # short site tagline
  1st IEEE Workshop on Distributed, Secure, and Trustworthy Intelligence with LLMs (IEEE DISTILL 2025)
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme. Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
keywords: workshop, IEEE, LLM, privacy, federated-learning, security, trustworthy-AI

lang: en
icon: 🧠

url: "https://ieeedistill.github.io"  
baseurl: ""                           
last_updated: false
impressum_path:

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------

rss_icon: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
max_width: 1000px

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------

serve_og_meta: false
serve_schema_org: false
og_image:

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: YOUR_USERNAME        # replace YOUR_USERNAME
gitlab_username:
twitter_username:
linkedin_username:
scholar_userid:
orcid_id:
medium_username:
quora_username:
publons_id:
research_gate_profile:
blogger_url:
work_url:
keybase_username:
wikidata_id:
dblp_url:
stackoverflow_id:

contact_note: >
  For questions about paper submissions and program details, please use the email above.

google_analytics: G-XZVGGMRFQG       # if you have one
google_site_verification:
bing_site_verification:
panelbear_analytics:

# -----------------------------------------------------------------------------
# Blog (not used for workshop pages, but you can enable news posts)
# -----------------------------------------------------------------------------

blog_name: DISTILL News
blog_description: Announcements and updates for IEEE DISTILL 2025
permalink: /news/:year/:title/
pagination:
  enabled: true
disqus_shortname:

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    output: true
    permalink: /news/:path/
news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
highlight_theme_light: github
highlight_theme_dark: native
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ['_pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
keep_files:
  - CNAME
  - .nojekyll

plugins:
  - jekyll-archives
  - jekyll-diagrams
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-imagemagick
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-twitter-plugin
  - jemoji

defaults:
  - scope:
      path: "assets/**/*.*"
    values:
      sitemap: false

# -----------------------------------------------------------------------------
# Optimization & extras (you can leave these as-is or tweak per your needs)
# -----------------------------------------------------------------------------

remove_HTML_comments: false
beautify: false
minify: false
sass:
  style: compressed

# -----------------------------------------------------------------------------
# Archives, Scholar, Images, Diagrams, etc.
# -----------------------------------------------------------------------------
jekyll-archives:
  enabled: [year, tags, categories]
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: '/news/:year/'
    tag: '/news/tag/:name/'
    category: '/news/category/:name/'

scholar:
  last_name: Einstein
  first_name: [Albert, A.]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: "@*"

imagemagick:
  enabled: true
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
  output_formats:
    webp: "-quality 75%"

jekyll-diagrams: {}

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics:    true
enable_panelbear_analytics: false
enable_google_verification: false
enable_bing_verification:   false
enable_masonry:             true
enable_math:                true
enable_tooltips:            false
enable_darkmode:            false
enable_navbar_social:       false
enable_project_categories:  false
enable_medium_zoom:         true

# -----------------------------------------------------------------------------
# Library versions (usually you can leave these as-is)
# -----------------------------------------------------------------------------

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
bootstrap:
  version: "4.6.1"
  integrity:
    css: "sha256-DF7Zhf293AJxJNTmh5zhoYYIMs2oXitRfBjY+9L//AY="
    js: "sha256-SyTu6CwrfOhaznYZPoolVw2rxoY7lKYKQvqbtqN93HI="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
mathjax:
  version: "3.2.0"
masonry:
  version: "4.2.2"
  integrity: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
mdb:
  version: "4.20.0"
  integrity:
    css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
    js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="
popper:
  version: "2.11.2"
  integrity: "sha256-l/1pMF/+J4TThfgARS6KwWrk/egwuVvhRzfLAMQ6Ds4="
medium_zoom:
  version: "1.0.6"
  integrity: "sha256-EdPgYcPk/IIrw7FYeuJQexva49pVRZNmt3LculEr7zM="
